openapi: "3.0.0"
info:
  version: 1.0.0
  title: WEB API
  license:
    name: MIT
servers:
  - url: https://localhost:3001
paths:
  ######################
  # login google
  ######################
  /auth/google:
    get:
      description: |
        google oauth
      operationId: login
      x-eov-operation-handler: routes/auth
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
        '302':
          description: Moved Permanently
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/google/callback:
    get:
      description: |
        google oauth
      operationId: callback
      x-eov-operation-handler: routes/auth
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    oauth:
      properties:
        accesstoken:
          type: string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string