openapi: "3.0.0"
info:
  version: 1.0.0
  title: WEB API
  license:
    name: MIT
servers:
  - url: http://localhost:3000
paths:
  /ping:
    get:
      description: |
        ping then pong
      operationId: pingpong
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string